import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { fontSans } from '@/config/fonts';
import clsx from "clsx";

export const metadata: Metadata = {
    title: "KidGo",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
};
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html suppressHydrationWarning lang="en">
        <body className={clsx("font-sans antialiased", fontSans.className)}>
        <Providers>
            {children}
        </Providers>
        </body>
        </html >
    );
}